aaa
posse-ap/gen3.0-inose-yuudai pull request #1
Opened 2022-06-26 03:07 UTC by inose-yuudai

2022-06-28 08:58 UTC, bigdragon0610 reviewed
プルリクのテンプレ使って下さい！下に貼っておきます
あとタイトルとかも人が見てわかるように設定できるといいですね〜

---
```
## 今週の課題
- [ ] チェックポイント1
- [ ] チェックポイント2

## 注意点やレビュワーに伝えたいこと(あれば)

## 課題が終わっている証跡(スクショ)
```

2022-06-28 08:58 UTC, bigdragon0610 commented on README.md
> -クァwせdrftgyふじこクァwせdrftgyふじこ
コンフリクト起きてます！
縦モクなどで聞いてみるといいです

2022-06-28 08:58 UTC, bigdragon0610 commented on index.html
> +<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
インデント揃えるの意識しましょう〜

2022-06-28 08:58 UTC, bigdragon0610 commented on index.html
> +        <div class="instagram"><img src="/imgs/ 10.png" alt=""></div>
srcのところ、/img/ 10.png みたいにスペース開いてるのが気になります

2022-06-28 08:58 UTC, bigdragon0610 commented on posse課題/トップ/index2.html
> +<!DOCTYPE html>
フォルダ名が日本語なの気になります！
index2.htmlというように番号をつけることはあまりしないです

2022-06-28 08:58 UTC, bigdragon0610 commented on posse課題/トップ/index2.html
> +     a
がんばろう！

2022-06-28 08:58 UTC, bigdragon0610 commented on style.css
> +
いらない空行は消そう！

2022-07-12 08:05 UTC, niijima1229 commented
ぜひ、見た目のスクショを送っていただけるとどこまで完成しているのかが見れるので嬉しいです。
あと、何を作っているのかなどの説明をPRには記載していただくようにお願いします

2022-07-17 14:37 UTC, inose-yuudai commented
test

2022-07-17 14:40 UTC, inose-yuudai commented
クイズページを作成中　選択肢を押すと色が変わる程度まではできた。

2022-07-17 14:42 UTC, inose-yuudai commented
file:///Users/inoseyudai/workspace/gen3.0-inose-yuudai/posse%E8%AA%B2%E9%A1%8C/%E3%82%AF%E3%82%A4%E3%82%B9%E3%82%99/index.html

2022-08-02 04:28 UTC, inose-yuudai commented
<img width="1440" alt="9F28CD74-1429-424A-A69E-0CC75C22FAAD" src="https://user-images.githubusercontent.com/107345190/182291775-b03d3a42-9fbb-46fd-bedd-3af670ebc694.png">

2022-08-09 01:27 UTC, daiki-sato requested changes

2022-08-09 01:27 UTC, daiki-sato commented on posse課題/クイズ/js/quiz.js
> +let button611 = document.getElementById("6-t");
`button611`

変数名が分かりにくいので、変数名見ただけで何のことかわかるような名前にしていただけると

2022-09-12 09:30 UTC, merged