Feature/week9
posse-ap/gen3.0-inose-yuudai pull request #5
Opened 2022-08-14 11:47 UTC by inose-yuudai

2022-08-14 11:54 UTC, inose-yuudai commented
## 今週の課題
- [ レスポンシブデザイン] 


## 注意点やレビュワーに伝えたいこと
遅れを取り戻してレスポンシブに入ったばかりなので進んでいません。今週からプルリクの方法を正しいやり方？に変えたんですけどこれでいいのかよくわかっていません

2022-08-15 02:18 UTC, daiki-sato requested changes
フォルダ名は英語の方がいいです。
<img width="118" alt="スクリーンショット 2022-08-15 11 18 09" src="https://user-images.githubusercontent.com/71477876/184566660-4eef448f-8b06-48eb-abec-aea258f94b10.png">
<img width="192" alt="スクリーンショット 2022-08-15 11 18 14" src="https://user-images.githubusercontent.com/71477876/184566662-7ad8ba8b-00a0-4858-9990-9fd58b66da12.png">

2022-08-15 02:26 UTC, daiki-sato commented on posse課題/トップ/index.html
> +            function() {
これ不要？

2022-08-15 02:26 UTC, daiki-sato commented on posse課題/トップ/style/test.html
> +<section class="quiz">
sectionの閉じタグがない？

2022-08-15 02:26 UTC, daiki-sato commented on posse課題/トップ/style/test.html
> +                <div class=" p-quiz-box-answer-correct js-answerBox  is-correct is-incorrect ">
divの閉じタグがない？

2022-08-15 06:59 UTC, merged